### ISSUE TITLE
feature request submit jobs by priority rather than by jobname

### ISSUE THREAD

**Issue by fpbarthel** [sahilseth/flowr#10]
Currently flowr submits jobs to HPC by the jobname. Eg. you want to submit 5 independent flowr pipelines (say A-E) with each 50 (1-50) dependant sub-jobs. Submission is then done sequentially for each jobname, starting with pipeline A sub-job 1, then sub-job 2, etc... Because of the delay in submitting jobs, this can take a while.

Can you make it so when you submit multiple jobnames it submits in order of priority, eg first A1, then B1 (rather than A2) etc..?

--

**Comment by sahilseth** [comment]
Hi @fpbarthel 

If say B1 needs A1 this is certainly possible. Considering a scenario where B1 need all A1-A10, then submitting all of A first is imperative, before submitting B.

How long does the submission take ? and how long does processing take, just curious?

Possible solutions outside the scope of flowr:
- In case A - E are completely independent, may be you could submit them in parallel using separate ssh sessions?

I have a feeling for some of the platforms, this delay is due to the login server load, even if one makes submission parallel, it would not speed it up the whole process.

Also submission may be slow or fast depending on how fast HPCC can process requests. I have seen some other HPCC which are super fast in processing submissions.

**Comment by fpbarthel** [comment]
I'm not sure if I'm making my point clear, what I mean is that you can speed up processing by a lot by submitting jobs in the order of which they can run rather than sequentially by jobname. I can probably explain better in person.

**Comment by sahilseth** [comment]
Here is the current hierarchy of submission:
- Group by sample name:
  - group by jobname (step name)
     - submit each sub-process of a step

Sure we can discuss more...
