### ISSUE TITLE
Ability to re-run after dependency has changed

### ISSUE THREAD

**Issue by Pgibas** [sahilseth/flowr#54]
Is it possible to add the ability to re-run analysis if one of the dependencies (eg., file or code.sh) has changed?

**Comment by sahilseth** [comment]
Though am not completely sure what you would like to do, but I will go ahead and say its possible. 

Let us say we have this flowmat, in which 

- `sleep` was successful
- `merge` has a error, since `create_tmp` had a issue and need to be corrected.

```
samplename	jobname	cmd
sample1	sleep	sleep 10 && sleep 2;echo 'hello'
sample1	sleep	sleep 11 && sleep 8;echo 'hello'
sample1	sleep	sleep 11 && sleep 17;echo 'hello'
sample1	create_tmp	head -c 100000 /dev/urandom > sample1_tmp_1
sample1	create_tmp	head -c 100000 /dev/urandom > sample1_tmp_2
sample1	create_tmp	head -c 100000 /dev/urandom > sample1_tmp_3
sample1	merge	cat sample1_tmp_1 sample1_tmp_2 sample1_tmp_3 > sample1_merged
sample1	size	du -sh sample1_merged; echo 'MY shell:' $SHELL
```

flowmat: https://github.com/sahilseth/flowr/edit/master/inst/pipelines/sleep_pipe.tsv
flowdef: https://github.com/sahilseth/flowr/edit/master/inst/pipelines/sleep_pipe.def


Solution is to start from `create_tmp`, and here is how we would do it:

```
flowmat=<new tsv with new updated commands for create_tmp>
flowr rerun x=<path to previous run> mat=$flowmat start_from=create_tmp
```

Please correct me if this is not what you intend to do. Also, an example from your side would help.

hope this helps !
